## SQL at Scale with Spark SQL

Welcome to the SQL mini project. For this project, you will use the Databricks Platform and work through a series of exercises using Spark SQL. The dataset size may not be too big but the intent here is to familiarize yourself with the Spark SQL interface which scales easily to huge datasets, without you having to worry about changing your SQL queries. 

The data you need is present in the mini-project folder in the form of three CSV files. This data will be imported in Databricks to create the following tables under the __`country_club`__ database.

<br>
1. The __`bookings`__ table,
2. The __`facilities`__ table, and
3. The __`members`__ table.

You will be uploading these datasets shortly into the Databricks platform to understand how to create a database within minutes! Once the database and the tables are populated, you will be focusing on the mini-project questions.

In the mini project, you'll be asked a series of questions. You can solve them using the databricks platform, but for the final deliverable,
please download this notebook as an IPython notebook (__`File -> Export -> IPython Notebook`__) and upload it to your GitHub.

### Creating the Database

We will first create our database in which we will be creating our three tables of interest

In [0]:
%sql 
drop database if exists country_club cascade;
create database country_club;
show databases;

databaseName
country_club
default

### Creating the Tables

In this section, we will be creating the three tables of interest and populate them with the data from the CSV files already available to you. 
To get started, first upload the three CSV files to the DBFS as depicted in the following figure

![](https://i.imgur.com/QcCruBr.png)


Once you have done this, please remember to execute the following code to build the dataframes which will be saved as tables in our database

In [0]:
# File location and type
file_location_bookings = "/FileStore/tables/Bookings.csv"
file_location_facilities = "/FileStore/tables/Facilities.csv"
file_location_members = "/FileStore/tables/Members.csv"

file_type = "csv"

# CSV options
infer_schema = "true"
first_row_is_header = "true"
delimiter = ","

# The applied options are for CSV files. For other file types, these will be ignored.
bookings_df = (spark.read.format(file_type) 
                    .option("inferSchema", infer_schema) 
                    .option("header", first_row_is_header) 
                    .option("sep", delimiter) 
                    .load(file_location_bookings))

facilities_df = (spark.read.format(file_type) 
                      .option("inferSchema", infer_schema) 
                      .option("header", first_row_is_header) 
                      .option("sep", delimiter) 
                      .load(file_location_facilities))

members_df = (spark.read.format(file_type) 
                      .option("inferSchema", infer_schema) 
                      .option("header", first_row_is_header) 
                      .option("sep", delimiter) 
                      .load(file_location_members))

### Viewing the dataframe schemas

We can take a look at the schemas of our potential tables to be written to our database soon

In [0]:
print('Bookings Schema')
bookings_df.printSchema()
print('Facilities Schema')
facilities_df.printSchema()
print('Members Schema')
members_df.printSchema()

Bookings Schema
root
 |-- bookid: integer (nullable = true)
 |-- facid: integer (nullable = true)
 |-- memid: integer (nullable = true)
 |-- starttime: string (nullable = true)
 |-- slots: integer (nullable = true)

Facilities Schema
root
 |-- facid: integer (nullable = true)
 |-- name: string (nullable = true)
 |-- membercost: double (nullable = true)
 |-- guestcost: double (nullable = true)
 |-- initialoutlay: integer (nullable = true)
 |-- monthlymaintenance: integer (nullable = true)

Members Schema
root
 |-- memid: integer (nullable = true)
 |-- surname: string (nullable = true)
 |-- firstname: string (nullable = true)
 |-- address: string (nullable = true)
 |-- zipcode: integer (nullable = true)
 |-- telephone: string (nullable = true)
 |-- recommendedby: integer (nullable = true)
 |-- joindate: string (nullable = true)

### Create permanent tables
We will be creating three permanent tables here in our __`country_club`__ database as we discussed previously with the following code

In [0]:
permanent_table_name_bookings = "country_club.Bookings"
bookings_df.write.format("parquet").saveAsTable(permanent_table_name_bookings)

permanent_table_name_facilities = "country_club.Facilities"
facilities_df.write.format("parquet").saveAsTable(permanent_table_name_facilities)

permanent_table_name_members = "country_club.Members"
members_df.write.format("parquet").saveAsTable(permanent_table_name_members)

### Refresh tables and check them

In [0]:
%sql
use country_club;
REFRESH table bookings;
REFRESH table facilities;
REFRESH table members;
show tables;

database,tableName,isTemporary
country_club,bookings,false
country_club,facilities,false
country_club,members,false

### Test a sample SQL query

__Note:__ You can use __`%sql`__ at the beginning of a cell and write SQL queries directly as seen in the following cell. Neat isn't it!

In [0]:
%sql
select * from bookings limit 3

bookid,facid,memid,starttime,slots
0,3,1,2012-07-03 11:00:00,2
1,4,1,2012-07-03 08:00:00,2
2,6,0,2012-07-03 18:00:00,2

#### Q1: Some of the facilities charge a fee to members, but some do not. Please list the names of the facilities that do.

In [0]:
%sql
select * from facilities limit 3;

facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
0,Tennis Court 1,5.0,25.0,10000,200
1,Tennis Court 2,5.0,25.0,8000,200
2,Badminton Court,0.0,15.5,4000,50

In [0]:
%sql
select name from facilities where membercost = 0;

name
Badminton Court
Table Tennis
Snooker Table
Pool Table

####  Q2: How many facilities do not charge a fee to members?

In [0]:
%sql
select count(*) from facilities where membercost = 0;

count(1)
4

#### Q3: How can you produce a list of facilities that charge a fee to members, where the fee is less than 20% of the facility's monthly maintenance cost? 
#### Return the facid, facility name, member cost, and monthly maintenance of the facilities in question.

In [0]:
%sql
describe table facilities;

col_name,data_type,comment
facid,int,null
name,string,null
membercost,double,null
guestcost,double,null
initialoutlay,int,null
monthlymaintenance,int,null

In [0]:
%sql
select facid, name, membercost, monthlymaintenance from facilities where membercost < monthlymaintenance/5;

facid,name,membercost,monthlymaintenance
0,Tennis Court 1,5.0,200
1,Tennis Court 2,5.0,200
2,Badminton Court,0.0,50
3,Table Tennis,0.0,10
4,Massage Room 1,9.9,3000
5,Massage Room 2,9.9,3000
6,Squash Court,3.5,80
7,Snooker Table,0.0,15
8,Pool Table,0.0,15

#### Q4: How can you retrieve the details of facilities with ID 1 and 5? Write the query without using the OR operator.

In [0]:
%sql
select * from facilities where facid IN (1,5);

facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
1,Tennis Court 2,5.0,25.0,8000,200
5,Massage Room 2,9.9,80.0,4000,3000

#### Q5: How can you produce a list of facilities, with each labelled as 'cheap' or 'expensive', depending on if their monthly maintenance cost is more than $100? 
#### Return the name and monthly maintenance of the facilities in question.

In [0]:
%sql
select name, monthlymaintenance, case when monthlymaintenance > 100 then 'expensive' else 'cheap' end as label from facilities;

name,monthlymaintenance,label
Tennis Court 1,200,expensive
Tennis Court 2,200,expensive
Badminton Court,50,cheap
Table Tennis,10,cheap
Massage Room 1,3000,expensive
Massage Room 2,3000,expensive
Squash Court,80,cheap
Snooker Table,15,cheap
Pool Table,15,cheap

#### Q6: You'd like to get the first and last name of the last member(s) who signed up. Do not use the LIMIT clause for your solution.

In [0]:
%sql
select * from members limit 5;

memid,surname,firstname,address,zipcode,telephone,recommendedby,joindate
0,GUEST,GUEST,GUEST,0,(000) 000-0000,null,2012-07-01 00:00:00
1,Smith,Darren,"8 Bloomsbury Close, Boston",4321,555-555-5555,null,2012-07-02 12:02:05
2,Smith,Tracy,"8 Bloomsbury Close, New York",4321,555-555-5555,null,2012-07-02 12:08:23
3,Rownam,Tim,"23 Highway Way, Boston",23423,(844) 693-0723,null,2012-07-03 09:32:15
4,Joplette,Janice,"20 Crossing Road, New York",234,(833) 942-4710,1,2012-07-03 10:25:05

In [0]:
%sql
select firstname, surname from members m1 where not exists ( select * from members m2 where m2.joindate > m1.joindate);

firstname,surname
Darren,Smith

####  Q7: How can you produce a list of all members who have used a tennis court?
- Include in your output the name of the court, and the name of the member formatted as a single column. 
- Ensure no duplicate data
- Also order by the member name.

In [0]:
%sql
select * from  members limit 3;

memid,surname,firstname,address,zipcode,telephone,recommendedby,joindate
0,GUEST,GUEST,GUEST,0,(000) 000-0000,null,2012-07-01 00:00:00
1,Smith,Darren,"8 Bloomsbury Close, Boston",4321,555-555-5555,null,2012-07-02 12:02:05
2,Smith,Tracy,"8 Bloomsbury Close, New York",4321,555-555-5555,null,2012-07-02 12:08:23

In [0]:
%sql
select * from facilities limit 3;

facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
0,Tennis Court 1,5.0,25.0,10000,200
1,Tennis Court 2,5.0,25.0,8000,200
2,Badminton Court,0.0,15.5,4000,50

In [0]:
%sql
select * from  bookings limit 3;

bookid,facid,memid,starttime,slots
0,3,1,2012-07-03 11:00:00,2
1,4,1,2012-07-03 08:00:00,2
2,6,0,2012-07-03 18:00:00,2

In [0]:
%sql
select DISTINCT(CONCAT(m.firstname, ' ', m.surname)) as fullname, f.name from members m join bookings b on b.memid = m.memid left join facilities f on f.facid = b.facid where f.name like 'Tennis%' order by fullname desc;

fullname,name
Tracy Smith,Tennis Court 2
Tracy Smith,Tennis Court 1
Timothy Baker,Tennis Court 1
Timothy Baker,Tennis Court 2
Tim Rownam,Tennis Court 1
Tim Rownam,Tennis Court 2
Tim Boothe,Tennis Court 2
Tim Boothe,Tennis Court 1
Ramnaresh Sarwin,Tennis Court 1
Ramnaresh Sarwin,Tennis Court 2
Ponder Stibbons,Tennis Court 2
Ponder Stibbons,Tennis Court 1
Nancy Dare,Tennis Court 1
Nancy Dare,Tennis Court 2
Millicent Purview,Tennis Court 2
Matthew Genting,Tennis Court 1
John Hunt,Tennis Court 1
John Hunt,Tennis Court 2
Joan Coplin,Tennis Court 1
Jemima Farrell,Tennis Court 1
Jemima Farrell,Tennis Court 2
Janice Joplette,Tennis Court 1
Janice Joplette,Tennis Court 2
Jack Smith,Tennis Court 2
Jack Smith,Tennis Court 1
Henrietta Rumney,Tennis Court 2
Gerald Butters,Tennis Court 1
Gerald Butters,Tennis Court 2
GUEST GUEST,Tennis Court 2
GUEST GUEST,Tennis Court 1
Florence Bader,Tennis Court 1
Florence Bader,Tennis Court 2
Erica Crumpet,Tennis Court 1
Douglas Jones,Tennis Court 1
David Pinker,Tennis Court 1
David Jones,Tennis Court 2
David Jones,Tennis Court 1
David Farrell,Tennis Court 2
David Farrell,Tennis Court 1
Darren Smith,Tennis Court 2
Charles Owen,Tennis Court 1
Charles Owen,Tennis Court 2
Burton Tracy,Tennis Court 2
Burton Tracy,Tennis Court 1
Anne Baker,Tennis Court 1
Anne Baker,Tennis Court 2

#### Q8: How can you produce a list of bookings on the day of 2012-09-14 which will cost the member (or guest) more than $30? 

- Remember that guests have different costs to members (the listed costs are per half-hour 'slot')
- The guest user's ID is always 0. 

#### Include in your output the name of the facility, the name of the member formatted as a single column, and the cost.

- Order by descending cost, and do not use any subqueries.

In [0]:
%sql
select b.bookid CONCAT(firstname, ' ', surname) as fullname, memid

In [0]:
%sql
SELECT b.bookid, first(b.memid) as memid, first(b.slots) as slots, first(b.starttime), first(f.name), first(f.membercost), first(f.guestcost), CONCAT(first(m.firstname), ' ', first(m.surname)) as fullname, (case when first(b.memid) = 0 then first(b.slots) * first(f.guestcost) else first(b.slots) * first(f.membercost) end) as bookingcost from bookings b left join facilities f on b.facid = f.facid left join members m on m.memid = b.memid group by b.bookid having bookingcost > 30 and  DATE(first(starttime)) = '2012-09-14'  order by bookingcost desc;

bookid,memid,slots,first(starttime),first(name),first(membercost),first(guestcost),fullname,bookingcost
2946,0,4,2012-09-14 11:00:00,Massage Room 2,9.9,80.0,GUEST GUEST,320.0
2937,0,2,2012-09-14 09:00:00,Massage Room 1,9.9,80.0,GUEST GUEST,160.0
2942,0,2,2012-09-14 16:00:00,Massage Room 1,9.9,80.0,GUEST GUEST,160.0
2940,0,2,2012-09-14 13:00:00,Massage Room 1,9.9,80.0,GUEST GUEST,160.0
2926,0,6,2012-09-14 17:00:00,Tennis Court 2,5.0,25.0,GUEST GUEST,150.0
2925,0,3,2012-09-14 14:00:00,Tennis Court 2,5.0,25.0,GUEST GUEST,75.0
2922,0,3,2012-09-14 19:00:00,Tennis Court 1,5.0,25.0,GUEST GUEST,75.0
2920,0,3,2012-09-14 16:00:00,Tennis Court 1,5.0,25.0,GUEST GUEST,75.0
2948,0,4,2012-09-14 09:30:00,Squash Court,3.5,17.5,GUEST GUEST,70.0
2941,13,4,2012-09-14 14:00:00,Massage Room 1,9.9,80.0,Jemima Farrell,39.6
2949,0,2,2012-09-14 12:30:00,Squash Court,3.5,17.5,GUEST GUEST,35.0
2951,0,2,2012-09-14 15:00:00,Squash Court,3.5,17.5,GUEST GUEST,35.0

#### Q9: This time, produce the same result as in Q8, but using a subquery.

In [0]:
%sql
select b.bookid, b.memid, (case b.memid = 0 then select guestcost from facilities where b.facid = facid else select membercost from facilities where b.facid = facid) * b.slots as bookingcost , (select CONCAT(firstname, ' ', surname) from members where b.memid = memid) as fullname from bookings b having bookingcost > 30 order by bookingcost desc;

In [0]:
  b

In [0]:
%sql
SELECT b.bookid, first(b.memid) as memid, first(b.slots) as slots, first(b.starttime), first(f.name), first(f.membercost), first(f.guestcost), CONCAT(first(m.firstname), ' ', first(m.surname)) as fullname, (case when first(b.memid) = 0 then first(b.slots) * first(f.guestcost) else first(b.slots) * first(f.membercost) end) as bookingcost from bookings b left join facilities f on b.facid = f.facid left join members m on m.memid = b.memid group by b.bookid having bookingcost > 30 and  DATE(first(starttime)) = '2012-09-14'  order by bookingcost desc;

bookid,memid,slots,first(starttime),first(name),first(membercost),first(guestcost),fullname,bookingcost
2946,0,4,2012-09-14 11:00:00,Massage Room 2,9.9,80.0,GUEST GUEST,320.0
2937,0,2,2012-09-14 09:00:00,Massage Room 1,9.9,80.0,GUEST GUEST,160.0
2942,0,2,2012-09-14 16:00:00,Massage Room 1,9.9,80.0,GUEST GUEST,160.0
2940,0,2,2012-09-14 13:00:00,Massage Room 1,9.9,80.0,GUEST GUEST,160.0
2926,0,6,2012-09-14 17:00:00,Tennis Court 2,5.0,25.0,GUEST GUEST,150.0
2925,0,3,2012-09-14 14:00:00,Tennis Court 2,5.0,25.0,GUEST GUEST,75.0
2922,0,3,2012-09-14 19:00:00,Tennis Court 1,5.0,25.0,GUEST GUEST,75.0
2920,0,3,2012-09-14 16:00:00,Tennis Court 1,5.0,25.0,GUEST GUEST,75.0
2948,0,4,2012-09-14 09:30:00,Squash Court,3.5,17.5,GUEST GUEST,70.0
2941,13,4,2012-09-14 14:00:00,Massage Room 1,9.9,80.0,Jemima Farrell,39.6
2949,0,2,2012-09-14 12:30:00,Squash Court,3.5,17.5,GUEST GUEST,35.0
2951,0,2,2012-09-14 15:00:00,Squash Court,3.5,17.5,GUEST GUEST,35.0

In [0]:
%sql
describe facilities;

col_name,data_type,comment
facid,int,null
name,string,null
membercost,double,null
guestcost,double,null
initialoutlay,int,null
monthlymaintenance,int,null

In [0]:
%sql
-- SELECT b.bookid, first(b.memid), first(b.slots), first(b.starttime), first(f.name), first(f.membercost), first(f.guestcost), CONCAT(first(m.firstname), ' ', first(m.surname)) as fullname, (case when first(b.memid) = 0 then first(b.slots) * first(f.guestcost) else first(b.slots) * first(f.membercost) end) as bookingcost from bookings b left join facilities f on b.facid = f.facid left join members m on m.memid = b.memid where (case when b.memid = 0 then b.slots * f.guestcost else b.slots * f.membercost end) > 30 and DATE(b.starttime) = '2012-09-14' group by b.bookid order by bookingcost desc;

#### Q10: Produce a list of facilities with a total revenue less than 1000.
- The output should have facility name and total revenue, sorted by revenue. 
- Remember that there's a different cost for guests and members!

In [0]:
%sql
-- SELECT f.facid, f.name, SUM(case when first(b.memid) = 0 then first(b.slots) * first(f.guestcost) else first(b.slots) * first(f.membercost) end) as bookingcost from bookings b left join facilities f on b.facid = f.facid left join members m on m.memid = b.memid where (case when b.memid = 0 then b.slots * f.guestcost else b.slots * f.membercost end) > 30 and DATE(b.starttime) = '2012-09-14' group by b.bookid order by bookingcost desc;

-- select f.facid, f.name, SUM(bookingcost) as revenue 
-- from facilities f, 
-- (case b.memid = 0 then select guestcost * b.slots from facilities else select membercost * b.slots from facilities end) bookingcost 
-- left join bookings b 
-- on b.facid = f.facid 
-- having revenue < 1000  
-- group by f.name 
-- order by revenue desc;